### ISSUE TITLE
Balloon Mode

### ISSUE THREAD

**Issue by tkschuler** [sparkfun/Qwiic_Titan_Gps_Py#1]
How do I set the XA1110 module to balloon mode?  

I set it to Balloon mode over Arduino, but then after launching the module on a HAB, data cut out at 10km, so it seems like I need to set it to Balloon mode after every boot-up. For my setup I also need a way to do this from a Raspberry Pi over I2C.

**Comment by santaimpersonator** [comment]
I'm going to close this issue because it is a technical assistance question and has been sitting for a while.

In regards to your question:

- This appears to be a technical assistance question, which should be posted on [our forum](https://forum.sparkfun.com/) for our technical support team.
    - *They do not actively monitor the GitHub issues of all our repositories.*
- For more information on utilizing balloon mode, please refer to the [PMTK packet user manual](https://cdn.sparkfun.com/assets/parts/1/2/2/8/0/PMTK_Packet_User_Manual.pdf).
